server:
  port: 8080

spring:
  application:
    name: cloudPayment80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 952714


#eureka:
#  client:
#    service-url: http://localhost:7001/eureka
#          #是否将自己注册进EurekaServer默认为true
#      register-with-eureka: true
#          #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#      fetch-registry: true
#eureka:
#  client:
#    service-url:
#    register-with-eureka: true
#    fetch-registry: true
#    defaultZone: http://localhost:7001/eureka
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7002/eureka
